### ISSUE TITLE
NetBSD package now available

### ISSUE THREAD

**Issue by 0323pin** [kdr-aus/fitme#8]
Hi,

I've just packaged `fitme` for NetBSD and merged the package into our main branch.

Merge log for your reference, http://mail-index.netbsd.org/pkgsrc-changes/2023/10/02/msg283142.html

The package will be available for users of the current branch straight away. While users of the stable branch will get access to it by the end of December, as we cut the stable branches every quarter.

To install it on NetBSD users will simply need to run `pkgin install fitme`.

Regards

**Comment by kurtlawrence** [comment]
Thanks!

**Comment by 0323pin** [comment]
👍
